<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WPW-WANW-02" name="worldpay.QS.SeleniumRGNG.RiskProfilePageTest" tests="4" failures="1" timestamp="4 Nov 2015 18:53:22 GMT" time="26.596" errors="0">
  <testcase name="sectionExist" time="7.216" classname="worldpay.QS.SeleniumRGNG.RiskProfilePageTest"/>
  <testcase name="profileExist" time="6.223" classname="worldpay.QS.SeleniumRGNG.RiskProfilePageTest"/>
  <testcase name="profileTest" time="5.921" classname="worldpay.QS.SeleniumRGNG.RiskProfilePageTest"/>
  <testcase name="sectionTest" time="7.236" classname="worldpay.QS.SeleniumRGNG.RiskProfilePageTest">
    <failure type="java.lang.AssertionError" message="expected:&lt;Transaction specific&gt; but was:&lt;Profile specific&gt;">
      <![CDATA[java.lang.AssertionError: expected:<Transaction specific> but was:<Profile specific>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at worldpay.QS.SeleniumRGNG.RiskProfilePageTest.sectionTest(RiskProfilePageTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- sectionTest -->
</testsuite> <!-- worldpay.QS.SeleniumRGNG.RiskProfilePageTest -->
